### ISSUE TITLE
 Terminator need to highlight search string 

### ISSUE THREAD

**Issue by AdnanHodzic** [gnome-terminator/terminator#4]
Terminator has a built-in search (ctrl-shift-f - default keybinding), but it doesn't highlight the found text, which makes it fairly useless.

This bug is already [reported in launchpad (#271487) back in 2008.](https://bugs.launchpad.net/ubuntu/+source/terminator/+bug/271487)

**Comment by lazyfrosch** [comment]
@AdnanHodzic thanks for porting the issues that are relevant to you, could you please backlink to our new issues from Launchpad?

Just state something like: "I have created this issue with the new GitHub project: <link>"

This will help us improve the general awareness and people will find us when looking for a particular issue.

**Comment by AdnanHodzic** [comment]
@lazyfrosch most welcome, done.

**Comment by mattrose** [comment]
Found [this intriguing comment](https://bugs.launchpad.net/terminator/+bug/271487/comments/29). that suggests that it's fixed in rev 1773. I'll check my branch of the bzr code to see if there's something in ther

**Comment by mattrose** [comment]
Looks like it's fixed in Github.  @AdnanHodzic can you try out the latest code and see?

**Comment by AdnanHodzic** [comment]
@mattrose I have problem with installing from `master`, namely:

```
./setup.py install --record=install-files.txt
```

After I change `setup.py` line to `#!/usr/bin/env python3`, I still get an error:

```
./setup.py install --record=install-files.txt
/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running build_scripts
compiling po/nn.po -> build/mo/nn/terminator.mo
Building gettext files failed. Ensure you have gettext installed. Alternatively, try setup.py --without-gettext [build|install]
Error: [Errno 2] No such file or directory: 'msgfmt'
```

After which:

```
./setup.py --without-gettext install
/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running build_scripts
running install_lib
creating /usr/local/lib/python3.8/dist-packages/terminatorlib
error: could not create '/usr/local/lib/python3.8/dist-packages/terminatorlib': Permission denied
```

and finally:

```
sudo ./setup.py --without-gettext install
/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running build_scripts
running install_lib
creating /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/window.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/prefseditor.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/titlebar.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/version.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/util.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/plugin.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/layoutlauncher.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/preferences.glade -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/factory.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/signalman.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/terminal_popup_menu.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/config.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/debugserver.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
creating /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins
copying build/lib/terminatorlib/plugins/testplugin.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins
copying build/lib/terminatorlib/plugins/logger.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins
copying build/lib/terminatorlib/plugins/maven.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins
copying build/lib/terminatorlib/plugins/custom_commands.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins
copying build/lib/terminatorlib/plugins/activitywatch.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins
copying build/lib/terminatorlib/plugins/__init__.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins
copying build/lib/terminatorlib/plugins/terminalshot.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins
copying build/lib/terminatorlib/plugins/url_handlers.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins
copying build/lib/terminatorlib/terminator.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/freebsd.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/editablelabel.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/terminal.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/paned.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/searchbar.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/borg.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/notebook.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/keybindings.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/cwd.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/optionparse.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/layoutlauncher.glade -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/encoding.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/__init__.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/translation.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/container.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
copying build/lib/terminatorlib/ipc.py -> /usr/local/lib/python3.8/dist-packages/terminatorlib
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/window.py to window.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/prefseditor.py to prefseditor.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/titlebar.py to titlebar.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/version.py to version.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/util.py to util.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/plugin.py to plugin.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/layoutlauncher.py to layoutlauncher.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/factory.py to factory.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/signalman.py to signalman.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/terminal_popup_menu.py to terminal_popup_menu.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/config.py to config.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/debugserver.py to debugserver.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins/testplugin.py to testplugin.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins/logger.py to logger.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins/maven.py to maven.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins/custom_commands.py to custom_commands.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins/activitywatch.py to activitywatch.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins/__init__.py to __init__.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins/terminalshot.py to terminalshot.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/plugins/url_handlers.py to url_handlers.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/terminator.py to terminator.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/freebsd.py to freebsd.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/editablelabel.py to editablelabel.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/terminal.py to terminal.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/paned.py to paned.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/searchbar.py to searchbar.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/borg.py to borg.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/notebook.py to notebook.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/keybindings.py to keybindings.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/cwd.py to cwd.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/optionparse.py to optionparse.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/encoding.py to encoding.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/__init__.py to __init__.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/translation.py to translation.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/container.py to container.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/terminatorlib/ipc.py to ipc.cpython-38.pyc
running install_scripts
copying build/scripts-3.8/terminator -> /usr/local/bin
copying build/scripts-3.8/remotinator -> /usr/local/bin
changing mode of /usr/local/bin/terminator to 755
changing mode of /usr/local/bin/remotinator to 755
running install_data
copying terminator.wrapper -> /usr/local/bin
creating /usr/local/share/appdata
error: can't copy 'data/terminator.appdata.xml': doesn't exist or not a regular file
```
any ideas? I was simply following instructions in: `INSTALL` file.

**Comment by lazyfrosch** [comment]
Currently you will need to install `gettext` and `intltool` as external non-Python deps.

I plan to fix/improve this later.

**Comment by rixx** [comment]
I tried this in the current `master` and cannot see a highlight. I'm not sure the search works correctly, as even searching for "e" (which occurred a lot) only ever seemed to yield two results (or at least only one click on the Prev/Next button each).

**Comment by dgutov** [comment]
Seems to work all right in 1.92:

I initiate search, input the string (such as `e`), press RET and see the highlighting. Further RET presses loop between the matches (the highlighting moves).

**Comment by lazyfrosch** [comment]
I'm not seeing any highlight at the moment :weary:

**Comment by yuriw** [comment]
any clues how to make it work?

Here I see some suggestions that it may, but it would be useful if anybody who have been successful posted exact steps. Thx!

**Comment by mattrose** [comment]
So I just tried this on Fedora 31 with terminator-1.92-1 with a default configuration, both under X11 and wayland.  It works for me.  maybe there's an underlying problem with GTK, or VTE?

**Comment by yuriw** [comment]
i can't even try, PPA shows error

Err:11 http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu focal Release          
  404  Not Found [IP: 91.189.95.83 80]

Is it right PPA ?

**Comment by lazyfrosch** [comment]
This PPA is currently unmaintained as we have no access to the original Launchpad project.

**Comment by yuriw** [comment]
@lazyfrosch thx for the reply!
1.  do you think after 20.04 officially is out it will be the same PPA?
2.  is there any way to install latest terminator on 20.04 now ?

**Comment by AdnanHodzic** [comment]
@yuriw yes it's possible, but it's bit of a hackish ordeal. Regardless, let me guide you through it, first you need to install some dependencies:

```
sudo apt install gettext intltool python-six python-cairo python-psutil
```

Then since `python-configobj` is not in Ubuntu 20.04 repositories anymore, you need to [download it for 19.10 release](https://packages.ubuntu.com/eoan/all/python-configobj/download).

Followed by:

`sudo dpkg -i python-configobj_5.0.6-3_all.deb`

In case install fails, make sure to install any missing dependencies `sudo apt install -f`

Now make sure you have latest git changes and run:

```
sudo ./setup.py install --record=install-files.txt
```

Enjoy Terminator 1.92 :)

@lazyfrosch 

1. Unfortunately on Ubuntu 20.04 with Terminator 1.92 I still have the same problem in regards to search string not being highlighted.

2. Regarding mess with packaging, I recently had same problem with my [auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq) project. Which I resolved by creating a [snap package for it](https://github.com/AdnanHodzic/auto-cpufreq#snap-store).

If you want, create a ToDo item and I'll make a snap package for Terminator when I get a chance.

**Comment by yuriw** [comment]
@AdnanHodzic 
Thx I will try
- at what line exactly Terminator gets installed?
- hope this will not mess up my 20.04, will it ?

**Comment by AdnanHodzic** [comment]
@yuriw last line is what compiles and installs Terminator from git. 

What I explained is very straight forward and if things go south you can always run:
```
cat install-files.txt | xargs sudo rm -rf && rm -f
```

to remove all files that were created during the Terminator compilation process. However, if compiling software makes you uncomfortable I would definitely advise you against it :)

**Comment by yuriw** [comment]
@AdnanHodzic that depends on the final results :)

I assume I need to do 
git clone https://github.com/gnome-terminator/terminator/
  before next steps?
sudo ./setup.py install --record=install-files.txt

?

**Comment by AdnanHodzic** [comment]
@yuriw correct

**Comment by yuriw** [comment]
@AdnanHodzic 
well I did all steps and I think did not get 1.92

```
➜  ~ dpkg -l | grep terminator
ii  terminator                                    1.91-4ubuntu1                              all          multiple GNOME terminals in one window
```
See install-files.txt https://pastebin.com/G8hjyr3P

what's wrong ?

**Comment by AdnanHodzic** [comment]
@yuriw you need to remove `terminator` package which you have installed first. 

```
sudo apt remove terminator
```

Then run all commands I listed in Gnome terminal.

**Comment by yuriw** [comment]
@AdnanHodzic 
Ok copy that 
Will I keep all my saved profiles/layout?

**Comment by AdnanHodzic** [comment]
@yuriw no, settings will not be affected. I believe I gave you all information you need to resolve your problem (which could've been a separate issue). Let's not turn this bug report into a support ticket.

**Comment by yuriw** [comment]
@AdnanHodzic sure and I appropriate you help! 

But still after all steps - search does not work at all.
I'd be happy to provide all info needed if you wish.

**Comment by AdnanHodzic** [comment]
@yuriw you're most welcome. Yes, I confirmed the same in https://github.com/gnome-terminator/terminator/issues/4#issuecomment-617352723

Now I suggest we wait for feedback from @lazyfrosch or @mattrose

**Comment by yuriw** [comment]
@AdnanHodzic the only odd is =>

```
➜  ~ dpkg -l | grep terminator
➜  ~ 
```
is it expected ?

**Comment by yuriw** [comment]
@AdnanHodzic it's taking little time !
@lazyfrosch or @mattrose can you please comment?  At the moment my search does not work at all!

**Comment by lazyfrosch** [comment]
Please test #43

**Comment by yuriw** [comment]
@lazyfrosch it works like a charm ! 
Thank you !

**Comment by AdnanHodzic** [comment]
@lazyfrosch I can also confirm it works for me :partying_face:  I believe after changes are merged with `master` this issue can be closed.

**Comment by lazyfrosch** [comment]
Thanks for testing

**Comment by yuriw** [comment]
@lazyfrosch how long would it take till it can be installed via `apt install terminator` from ubuntu repos ?

**Comment by lazyfrosch** [comment]
I'm not an Ubuntu developer, or member, I can not publish updates to Ubuntu directly.

Once we have a change to adopt the original Launchpad project, I want to revive the PPAs.

**Comment by AdnanHodzic** [comment]
Ideally changes would first have to be pushed to Debian (Sid), which can be a process of its own. However, even if changes were pushed right now, it would take awhile (if ever at this point to make it into 20.04 release).

Which is the reason why [I was suggesting ](https://github.com/gnome-terminator/terminator/issues/4#issuecomment-617352723)to make Terminator a SNAP.

**Comment by yuriw** [comment]
With Snap being supported by 20.0 this is a great idea !

**Comment by dgutov** [comment]
I think the way to update a Debian package is to file a bug report that that request. You could also take a look at the existing reports and maybe reply to some that should already be fixed in the new version: https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=terminator;dist=unstable

A snap sounds good too. You could do both.

**Comment by lazyfrosch** [comment]
Guys, I'm the Debian maintainer, so I will update the package very close to a release. I also published a backport for buster.

Ubuntu works differently, and I can't push updates to there.

I'm going to revive the PPAs in the future, since I now have access to the original Launchpad project.

A snap doesn't make any sense for a terminal emulator, since the application is inside a jail, and only has very limited access to the host system.

**Comment by BachoSeven** [comment]
I agree. Snaps also do not respect the user's folder structure for configuration (XDG base directories) which means that plugins and config file would be hardcoded in ~/snap/terminator/current/, I think

**Comment by chaudum** [comment]
Unfortunately, I still have the issue of search results not being highlighted. I'm running Debian Bullseye with i3

```console
$ terminator --version
terminator 1.92

$ echo $VTE_VERSION 
6002

$ i3 --version
i3 version 4.18
```

**Comment by lazyfrosch** [comment]
@chaudum are you running git master?

**Comment by chaudum** [comment]
> @chaudum are you running git master?

Yes, I've tried with both the git master and the Debian package.

**Comment by lazyfrosch** [comment]
Can anyone reproduce this?

**Comment by chaudum** [comment]
> Can anyone reproduce this?

Hm, that may have been a false alarm, sorry. It seems to work on `master`, you are right. I had to start terminator from a different terminal (:man_facepalming: )

**Comment by lazyfrosch** [comment]
@chaudum you always need to make sure to either close terminator, or run the other version with `terminator -u` :+1:

**Comment by nmehta001** [comment]
I have version 1.92, directly from fedora repos and I have this bug

**Comment by mattrose** [comment]
The fix may not have made it into fedora yet.  I'll double-check and try and pull the fix in if it's not there.

**Comment by pratik705** [comment]
is the issue fixed for fedora? I am unable to use it on Fedora 32 with "terminator-1.92-3.fc32"

**Comment by jadekler** [comment]
I am not seeing this working as of `2.0.1`:

![20201019_121115](https://user-images.githubusercontent.com/3584893/96494892-39927200-1204-11eb-886b-61cf6290f398.png)

(built from https://github.com/gnome-terminator/terminator/releases/tag/v2.0.1)
