### ISSUE TITLE
Double input to broadcasted group

### ISSUE THREAD

**Issue by mikeperalta1** [gnome-terminator/terminator#623]
**Describe the bug**
When using multiple split panes and broadcasting to a group, the group members receive double the input sent from the selected pane. Screenshots attached below.

**To Reproduce**

1. Split the terminal to 2 or more panes
2. Assign all panes to the same group
3. Send keystrokes to one of the panes
4. Observe that the other panes don't receive accurate keystroke broadcast from the selected pane, but in fact double

**Expected behavior**
Each pane receiving keystrokes from the selected group member should only receive the correct input, rather than double.

**Screenshots**

![image](https://user-images.githubusercontent.com/26490778/180430976-56c5edf9-f5dd-43c3-8cd9-a3b9573f2983.png)

![image](https://user-images.githubusercontent.com/26490778/180431362-47cf2eed-f396-41e4-9641-a9fc8c328c22.png)

**Desktop (please complete the following information):**
 - Ubuntu 
 - 22.04 LTS (Jammy Jellyfish)
 - X11 and XFCE

**Additional context**

Using latest version of terminator: 2.1.1

Config file (changed file extension from none to .txt because this form wouldn't accept as-is):
[config.txt](https://github.com/gnome-terminator/terminator/files/9167370/config.txt)

**Comment by sayaleeraut** [comment]
Facing the same issue as described above.
Version in use : 2.1.1-1

**Comment by pacientes** [comment]
It's so inconvenient.

**Comment by pacientes** [comment]
1. open `terminator` by sudo user
```bash
sudo vim /usr/bin/terminator
```

2. edit `ibus` environment
```python
# as-is
    username = pwd.getpwuid(os.getuid()).pw_name
    ibus_running = [p for p in psutil.process_iter() if p.name() == 'ibus-daemon' and p.username() == username]
    ibus_running = len(ibus_running) > 0
    if ibus_running:
        os.environ['IBUS_DISABLE_SNOOPER']='1'   # edit here

# to-be
    username = pwd.getpwuid(os.getuid()).pw_name
    ibus_running = [p for p in psutil.process_iter() if p.name() == 'ibus-daemon' and p.username() == username]
    ibus_running = len(ibus_running) > 0
    if ibus_running:
        os.environ['IBUS_DISABLE_SNOOPER']='0'   # edit here
```

**Comment by PenelopeFudd** [comment]
Also seeing this on Fedora 35 with Plasma 5.24.4 and terminator-2.1.1-3.fc35.noarch.rpm.
Even removed my config file /home/$username/.config/terminator/config and restarted terminator, no change.

**Comment by pacientes** [comment]
> > 1. open `terminator` by sudo user
> > 
> > ```shell
> > sudo vim /usr/bin/terminator
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. edit `ibus` environment
> > 
> > ```python
> > # as-is
> >     username = pwd.getpwuid(os.getuid()).pw_name
> >     ibus_running = [p for p in psutil.process_iter() if p.name() == 'ibus-daemon' and p.username() == username]
> >     ibus_running = len(ibus_running) > 0
> >     if ibus_running:
> >         os.environ['IBUS_DISABLE_SNOOPER']='1'   # edit here
> > 
> > # to-be
> >     username = pwd.getpwuid(os.getuid()).pw_name
> >     ibus_running = [p for p in psutil.process_iter() if p.name() == 'ibus-daemon' and p.username() == username]
> >     ibus_running = len(ibus_running) > 0
> >     if ibus_running:
> >         os.environ['IBUS_DISABLE_SNOOPER']='0'   # edit here
> > ```
> 
> This didn't fix the issue for me on 22.04.1 with GNOME 42.2.

It seems to be solved only in special cases.

My case is also 22.04.1 with GNOMW 42.4,
but `IBus` keyboard input method system and using Korean keyboard layout. (English system language)

**Comment by thsea** [comment]
我的系统是ubuntu20.04LTS
我也遇到了同样的问题。但是我修改为0或者1都没有解决问题
在os.environ['IBUS_DISABLE_SNOOPER']='1'  后面添加下面两行我的问题就解决了
```python3
# as-is
    username = pwd.getpwuid(os.getuid()).pw_name
    ibus_running = [p for p in psutil.process_iter() if p.name() == 'ibus-daemon' and p.username() == username]
    ibus_running = len(ibus_running) > 0
    if ibus_running:
        os.environ['IBUS_DISABLE_SNOOPER']='1' 
# to-be
    username = pwd.getpwuid(os.getuid()).pw_name
    ibus_running = [p for p in psutil.process_iter() if p.name() == 'ibus-daemon' and p.username() == username]
    ibus_running = len(ibus_running) > 0
    if ibus_running:
        os.environ['IBUS_DISABLE_SNOOPER']='1' 
        # add here
        os.environ['DBUS_SESSION_BUS_ADDRESS']='unix:abstract=/tmp/dbus-Pt6dtRyPkv,guid=e42fddaa778c1748c817e2d4630aeefa'
        os.environ['DBUS_SESSION_BUS_PID']='21012' 
```
这些环境变量的值可以通过下面的命令查看
```bash
echo $(dbus-launch) 
```

**Comment by mattrose** [comment]
should be fixed by #674

**Comment by ehsjoar** [comment]
#674 did not fix it for me. I built from HEAD (403bf540) and I still have the issue
* debian 11.5
*  plasma 5.20

**Comment by MrIsak** [comment]
This is issue still occurs:

- Terminal version 2.1.3-1 (installed from PPA)
- Ubuntu 22.04.2 LTS
- XDG_SESSION_TYPE="x11"
- Gnome version 42.5

**Comment by mattrose** [comment]
Yeah, this is a bug in ibus, and and terminator is not the only program affected

**Comment by lamnguyenx** [comment]
> 1. open `terminator` by sudo user
> 
> ```shell
> sudo vim /usr/bin/terminator
> ```
> 
> 2. edit `ibus` environment
> 
> ```python
> # as-is
>     username = pwd.getpwuid(os.getuid()).pw_name
>     ibus_running = [p for p in psutil.process_iter() if p.name() == 'ibus-daemon' and p.username() == username]
>     ibus_running = len(ibus_running) > 0
>     if ibus_running:
>         os.environ['IBUS_DISABLE_SNOOPER']='1'   # edit here
> 
> # to-be
>     username = pwd.getpwuid(os.getuid()).pw_name
>     ibus_running = [p for p in psutil.process_iter() if p.name() == 'ibus-daemon' and p.username() == username]
>     ibus_running = len(ibus_running) > 0
>     if ibus_running:
>         os.environ['IBUS_DISABLE_SNOOPER']='0'   # edit here
> ```

This worker for with with GNOME Shell 3.36.9 on Ubuntu 20.04

**Comment by awsms** [comment]
> should be fixed by #674

Not fixed, issue is still here...

**Comment by mattrose** [comment]
This is not an issue with terminator, but a bug in ibus.

**Comment by MMI** [comment]
For the next person that finds this via `$search_engine` that is having this problem and only has an en-us keyboard setup --  simply running `ibus exit` can solve the problem.  `ibus start` will bring the problem back -- even on a running instance of terminator.

Since I have no knowledge or interest in `ibus` this is a satisfactory workaround for me.

**Comment by mauricio-sousa** [comment]
I have tested a workaround:

1. Edit the file `/usr/share/applications/terminator.desktop`.
2. Change the `Exec` line to:
   ```sh
   Exec=sh -c "GTK_IM_MODULE= setsid terminator"

**Comment by mattrose** [comment]
This bug is not necessarily in ibus itself, but in some of the language plugins.  It has been reported multiple times

**Comment by Sispheor** [comment]
Still present with `terminator 2.1.4` 🙃

**Comment by rm-minus-r-star** [comment]
`ibus exit` worked for me, though I had to also manually turn "broadcast off" from the menu. I didn't have broadcast on in the first place, that seems to have come along with the bug. `ibus exit` only turned off the duplication in other group shells.
